services:
  etcd0:
    container_name: etcd0
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.30.10:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://192.168.30.10:2379
      - ETCD_INITIAL_CLUSTER=etcd0=https://192.168.30.10:2380,etcd1=https://192.168.30.11:2380,etcd2=https://192.168.30.12:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_CERT_FILE=/opt/bitnami/etcd/certs/192.168.30.10.pem
      - ETCD_KEY_FILE=/opt/bitnami/etcd/certs/192.168.30.10-key.pem
      - ETCD_PEER_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_PEER_CERT_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.10.pem
      - ETCD_PEER_KEY_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.10-key.pem
      - ETCD_LOG_LEVEL=info
      - ETCD_ACTIVE_ENDPOINTS=https://192.168.30.11:2380,https://192.168.30.12:2380
    networks:
      local:
        ipv4_address: 192.168.30.10
    ports:
      - 12379:2379
      - 12380:2380
    volumes:
      - ./data/etcd0:/opt/bitnami/etcd/data
      - ./certs/ca:/opt/bitnami/etcd/certs/ca
      - ./certs/etcd0:/opt/bitnami/etcd/certs

  etcd1:
    container_name: etcd1
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.30.11:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://192.168.30.11:2379
      - ETCD_INITIAL_CLUSTER=etcd0=https://192.168.30.10:2380,etcd1=https://192.168.30.11:2380,etcd2=https://192.168.30.12:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_CERT_FILE=/opt/bitnami/etcd/certs/192.168.30.11.pem
      - ETCD_KEY_FILE=/opt/bitnami/etcd/certs/192.168.30.11-key.pem
      - ETCD_PEER_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_PEER_CERT_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.11.pem
      - ETCD_PEER_KEY_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.11-key.pem
      - ETCD_LOG_LEVEL=info
      - ETCD_ACTIVE_ENDPOINTS=https://192.168.30.10:2380,https://192.168.30.12:2380
    networks:
      local:
        ipv4_address: 192.168.30.11
    ports:
      - 22379:2379
      - 22380:2380
    volumes:
      - ./data/etcd1:/opt/bitnami/etcd/data
      - ./certs/ca:/opt/bitnami/etcd/certs/ca
      - ./certs/etcd1:/opt/bitnami/etcd/certs

  etcd2:
    container_name: etcd2
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.30.12:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://192.168.30.12:2379
      - ETCD_INITIAL_CLUSTER=etcd0=https://192.168.30.10:2380,etcd1=https://192.168.30.11:2380,etcd2=https://192.168.30.12:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_CERT_FILE=/opt/bitnami/etcd/certs/192.168.30.12.pem
      - ETCD_KEY_FILE=/opt/bitnami/etcd/certs/192.168.30.12-key.pem
      - ETCD_PEER_TRUSTED_CA_FILE=/opt/bitnami/etcd/certs/ca/ca.pem
      - ETCD_PEER_CERT_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.12.pem
      - ETCD_PEER_KEY_FILE=/opt/bitnami/etcd/certs/peer-192.168.30.12-key.pem
      - ETCD_LOG_LEVEL=info
      - ETCD_ACTIVE_ENDPOINTS=https://192.168.30.10:2380,https://192.168.30.11:2380
    networks:
      local:
        ipv4_address: 192.168.30.12
    ports:
      - 32379:2379
      - 32380:2380
    volumes:
      - ./data/etcd2:/opt/bitnami/etcd/data
      - ./certs/ca:/opt/bitnami/etcd/certs/ca
      - ./certs/etcd2:/opt/bitnami/etcd/certs
    
networks:
  local:
    external: true