global:
  smtp_from: '<ur_email_here>'
  smtp_smarthost: '<smtp_smarthost>'
  smtp_auth_username: '<ur_email_here>'
  smtp_auth_password: '<smtp_authZ_code>'
  smtp_require_tls: false
  
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
  
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
    - to: '<ur_email_here>'
    
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
