services:
  zk1:
    container_name: zk1
    image: zookeeper
    hostname: zk1
    networks:
      local:
        ipv4_address: 192.168.50.11
    ports:
      - 12181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888:observer;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
    volumes:
      - ./datalog/zk1:/datalog

  zk2:
    container_name: zk2
    image: zookeeper
    hostname: zk2
    networks:
      local:
        ipv4_address: 192.168.50.12
    ports:
      - 22181:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888:observer;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
    volumes:
      - ./datalog/zk2:/datalog

  zk3:
    container_name: zk3
    image: zookeeper
    hostname: zk3
    networks:
      local:
        ipv4_address: 192.168.50.13
    ports:
      - 32181:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181 server.4=zk4:2888:3888:observer;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
    volumes:
      - ./datalog/zk3:/datalog

  zk4:
    container_name: zk4
    image: zookeeper
    hostname: zk4
    networks:
      local:
        ipv4_address: 192.168.50.14
    ports:
      - 42181:2181
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=0.0.0.0:2888:3888:observer;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7070"
    volumes:
      - ./datalog/zk4:/datalog

#  busybox:
#    container_name: busybox
#    image: busybox
#    command: sh -c "while true; do sleep 1; done"
#    networks:
#      local:
#        ipv4_address: 192.168.50.15

networks:
  local:
    external: true