services:
  master:
    container_name: master
    image: redis:alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.10
    ports:
      - "16380:6379"
    volumes:
      - ./config/master:/usr/local/etc/redis
    
  slave1:
    container_name: slave1
    image: redis:alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.11
    ports:
      - "16381:6379"
    volumes:
      - ./config/slave1:/usr/local/etc/redis
      
  slave2:
    container_name: slave2
    image: redis:alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.12
    ports:
      - "16382:6379"
    volumes:
      - ./config/slave2:/usr/local/etc/redis

  sentinel0:
    container_name: sentinel0
    image: redis:alpine
    command: ["redis-sentinel", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.20
    ports:
      - "26380:6379"
    volumes:
      - ./config/sentinel0:/usr/local/etc/redis
      - ./tmp:/tmp
    
  sentinel1:
    container_name: sentinel1
    image: redis:alpine
    command: ["redis-sentinel", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.21
    ports:
      - "26381:6379"
    volumes:
      - ./config/sentinel1:/usr/local/etc/redis
      - ./tmp:/tmp

  sentinel2:
    container_name: sentinel2
    image: redis:alpine
    command: ["redis-sentinel", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.22
    ports:
      - "26382:6379"
    volumes:
      - ./config/sentinel2:/usr/local/etc/redis
      - ./tmp:/tmp

networks:
  redis:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16