services:
  master:
    container_name: master
    image: redis:alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.10
    ports:
      - "16380:16380"
    volumes:
      - ./config/master.conf:/etc/redis/redis.conf:ro
    
  slave1:
    container_name: slave1
    image: redis:alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.11
    ports:
      - "16381:16381"
    volumes:
      - ./config/slave1.conf:/etc/redis/redis.conf:ro
  slave2:
    container_name: slave2
    image: redis:alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis:
        ipv4_address: 192.168.10.12
    ports:
      - "16382:16382"
    volumes:
      - ./config/slave2.conf:/etc/redis/redis.conf:ro

networks:
  redis:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24