services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      prometheus:
        ipv4_address: 192.168.40.10
    ports:
      - 19090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    networks:
      prometheus:
        ipv4_address: 192.168.40.11
    ports:
      - 19100:9100

  alert-manager:
    image: prom/alertmanager
    networks:
      prometheus:
        ipv4_address: 192.168.40.12
    ports:
      - 19093:9093
    volumes:
      - ./config/alertmanager:/etc/alertmanager

networks:
  prometheus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24