services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      local:
        ipv4_address: 192.168.40.10
    ports:
      - 19090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      # - ./data/prometheus:/prometheus
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    networks:
      local:
        ipv4_address: 192.168.40.11
    ports:
      - 19100:9100

  alert-manager:
    image: prom/alertmanager
    networks:
      local:
        ipv4_address: 192.168.40.12
    ports:
      - 19093:9093
    volumes:
      - ./config/alertmanager:/etc/alertmanager
  
  grafana:
    image: grafana/grafana
    networks:
      local:
        ipv4_address: 192.168.40.13
    ports:
      - 13000:3000
    volumes:
      # - ./data/grafana:/var/lib/grafana
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  local:
    external: true