services:
  grafana:
    image: grafana/grafana
    networks:
      local:
        ipv4_address: 192.168.40.14
    ports:
      - 13000:3000
    volumes:
      # - ./data/grafana:/var/lib/grafana
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus_reader

  prometheus_reader:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      local:
        ipv4_address: 192.168.40.15
    ports:
      - 19090:9090
    volumes:
      - ./config/prometheus/reader:/etc/prometheus
      # - ./data/prometheus:/prometheus
    depends_on:
      - prometheus_scraper

  prometheus_scraper:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      local:
        ipv4_address: 192.168.40.16
    ports:
      - 29090:9090
    volumes:
      - ./config/prometheus/scraper:/etc/prometheus
      # - ./data/prometheus:/prometheus
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    networks:
      local:
        ipv4_address: 192.168.40.17
    ports:
      - 19100:9100
  
networks:
  local:
    external: true